### ISSUE TITLE
Where is a good place for general discussion?

### ISSUE THREAD

**Issue by dereckrx** [alukach/playground#14]
For example, discussion about how to use Milestones. Does creating 'question' issues work for that? 

Obviously it it pertains to a piece of code or commit it belongs there, but curious if there's a good general spot.

**Comment by alukach** [comment]
To be honest, not really sure.  It would bring up a question regarding which questions belong in the Google Groups threads and which belong in the Github threads?  I'm imagining that general code design questions could live in Github while product design questions should live in the Google Group?  Thoughts?

Regarding milestones, it seems like they are a tool to assign a bunch of tasks to a single goal point (ie for ver 1.1.0, we want features X, Y, and Z in the code and bug fixes A and B, so we're going to assign those feature tasks and bug fixes to the 1.1.0 milestone).  This was based on poking around [Twitter Bootstrap's usage of milestones](https://github.com/twitter/bootstrap/issues/milestones?state=closed).

**Comment by ratsark** [comment]
A discussion about what the milestones should be definitely belongs on the Google Group; only technical stuff belongs here as we risk excluding the non-technical folk.

GitHub's pretty awesome so far!

**Comment by dereckrx** [comment]
Discussing what will go into version 1.0 belongs in Google Group, but discussing how to use the Github milestone feature might go here?

**Comment by ratsark** [comment]
That sounds right.
