### ISSUE TITLE
Compare GitHub issue tracking with Asana

### ISSUE THREAD

**Issue by ratsark** [alukach/playground#17]
GitHub is only appropriate to track project-level objectives, which may make it difficult to keep all issues assigned to a person straight and will make it impossible to track organization-level issues in GitHub.

I think we should consider keeping all of our issue tracking in Asana instead. I have no idea whether this is actually a good idea; I'm using consider to actually mean consider in this case, not that I think it's the correct path forward.

If we decide not to use Asana exclusively, we'll need to clearly delineate the type of tasks that belong in Asana from the type that belong in GitHub. For example, I wouldn't expect Liz to use GitHub on a regular basis (if ever). So if I need to assign a task to her that's related to the Graphs project, should I do that in Asana or GitHub?

**Comment by dereckrx** [comment]
This might be a good topic for the next video meeting as well.

**Comment by alukach** [comment]
Clearing out my "Assigned" section of Github.

2013... we were just young pups back then...
